---
title: "RFA analysis"
author: "Luis A. Figueroa, Paola SolíS Pazmiño & Oscar J. Ponce"
date: "2023-01-01"
knit: (function(inputFile, encoding) { rmarkdown::render(inputFile, encoding = encoding, output_file = paste0(dirname(inputFile),'/README.md')) })
output: github_document
---

<i> Analysis and visualization developed by [Luis A. Figueroa](https://twitter.com/LuisFig1706) and [Paola SolíS Pazmiño](paosolpaz18@gmail.com) </i>

```{r libraries, include= FALSE}
library(metafor)
library(openxlsx)
library(dplyr)
library(ggplot2)
library(tidyr)
library(reshape)
library(rmarkdown)
knitr::opts_chunk$set(fig.path = "RFA Figures/", dev='svg') # dev = 'png'
```


``` {r clean bocio, echo=FALSE, include= FALSE}
data1 <- read.xlsx("Base Bocio.xlsx")
databocio <- data1

names(databocio)[1]<- "id"
names(databocio)[2]<- "names"
names(databocio)[3]<- "age"
names(databocio)[4]<- "sex"
databocio$id[5] = "400821963(1)" # dobles resultados porque son dobles ablasiones en diferentes sitios
databocio$id[21] = "1303474009(1)"

datavol<- databocio[ ,1:9]
names(datavol)[5]<- "volbasal"
names(datavol)[6]<- "vol1m"
names(datavol)[7]<- "vol3m"
names(datavol)[8]<- "vol6m"
names(datavol)[9]<- "vol12m"
str(datavol)
datavol$vol1m <- as.numeric(datavol$vol1m)
datavol$vol3m <- as.numeric(datavol$vol3m)
datavol$vol6m <- as.numeric(datavol$vol6m)
datavol$sex <- as.factor(datavol$sex)
str(datavol)
summary(datavol)
sd(datavol$volbasal)
sd(datavol$vol1m)


datatsh<- databocio[ ,c(1:4, 11:22)]
names(datatsh)[5]<- "tshbasal"
names(datatsh)[6]<- "tsh1m"
names(datatsh)[7]<- "tsh3m"
names(datatsh)[8]<- "tsh6m"
names(datatsh)[9]<- "tsh12m"
names(datatsh)[12]<- "t4fbasal"
names(datatsh)[13]<- "t4f1m"
names(datatsh)[14]<- "t4f3m"
names(datatsh)[15]<- "t4f6m"
names(datatsh)[16]<- "t4f12m"
datatsh<- datatsh[ , - c(10:11)]
str(datatsh)
datatsh$tshbasal<-as.numeric(datatsh$tshbasal)
datatsh$tsh1m<-as.numeric(datatsh$tsh1m)
datatsh$tsh3m<-as.numeric(datatsh$tsh3m)
datatsh$t4fbasal<-as.numeric(datatsh$t4fbasal)
datatsh$t4f1m<-as.numeric(datatsh$t4f1m)
datatsh$t4f3m<-as.numeric(datatsh$t4f3m)
datatsh$t4f6m<-as.numeric(datatsh$t4f6m)
datatsh$t4f12m<-as.numeric(datatsh$t4f12m)
datatsh$sex<- as.factor(datatsh$sex)
str(datatsh)
summary(datatsh)
sd(datatsh$tshbasal)



datacosmetic<- databocio[ ,c(1:4, 23:28)]
names(datacosmetic)[5]<- "cosmbasal"
names(datacosmetic)[6]<- "cosm1m"
names(datacosmetic)[7]<- "cosm3m"
names(datacosmetic)[8]<- "cosm6m"
names(datacosmetic)[9]<- "cosm12m"
datacosmetic<- datacosmetic[,-c(10)]
datacosmetic$sex<- as.factor(datacosmetic$sex)
str(datacosmetic)
summary(datacosmetic)



datasymt<-databocio[, c(1:4,29:33)]
names(datasymt)[5]<- "symptbasal"
names(datasymt)[6]<- "sympt1m"
names(datasymt)[7]<- "sympt3m"
names(datasymt)[8]<- "sympt6m"
names(datasymt)[9]<- "sympt12m"
str(datasymt)


datareduc<-databocio[,c(1:4,35:38)]
names(datareduc)[5]<- "red1m"
names(datareduc)[6]<- "red3m"
names(datareduc)[7]<- "red6m"
names(datareduc)[8]<- "red12m"
str(datareduc)
datareduc$red6m<-as.numeric(datareduc$red6m)
datareduc$red12m<-as.numeric(datareduc$red12m)
str(datareduc)
datareduc$sex<- as.factor(datareduc$sex)
summary(datareduc)


datadiametro<-databocio[, c(1:4,39:43)]
str(datadiametro)
summary(datadiametro)
datadiametro$diametro3m<-as.numeric(datadiametro$diametro3m)
str(datadiametro)
summary(datadiametro)
sd(datadiametro$diametrobasal)
sd(datadiametro$diametro1m)
sd(datadiametro$diametro3m)
sd(datadiametro$diametro6m)
sd(datadiametro$diametro12m)



sd(datadiametro$diametro1m)
str(datadiametro)
datadiametro$diametro1m<- as.numeric(datadiametro$diametro1m)
datadiametro$diametro3m<- as.numeric(datadiametro$diametro3m)
sd(datadiametro$diametro1m)
mean(datadiametro$diametro1m)
sd(datadiametro$diametro3m)
sd(datadiametro$diametro6m)
```

``` {r clean micro, echo=FALSE, include= FALSE}
data2 <- read.xlsx("Base micro.xlsx")
datamicro <- data2[,-c(2:4)]

datamicro$id[2] = "603402470(1)" # dobles resultados porque son dobles ablasiones en diferentes sitios
datamicro$id[9] = "000000001" # dobles resultados porque son dobles ablasiones en diferentes sitios

datavolm<- datamicro[ ,c(1,6:10)]
str(datavolm)
datavolm$volbasal <- as.numeric(datavolm$volbasal)
datavolm$vol1m <- as.numeric(datavolm$vol1m)
datavolm$vol3m <- as.numeric(datavolm$vol3m)
datavolm$vol6m <- as.numeric(datavolm$vol6m)
summary(datavolm)
sd(datavolm$volbasal)
sd(datavolm$vol1m)


datatshm<- datamicro[ ,c(1, 11:14, 16:19)]
names(datatshm)[6]<- "t4f1m"
names(datatshm)[7]<- "t4f3m" 
names(datatshm)[8]<- "t4f6m"
names(datatshm)[9]<- "t4f12m"
str(datatshm)
datatshm$tsh1m<-as.numeric(datatshm$tsh1m)
datatshm$tsh6m<-as.numeric(datatshm$tsh6m)
datatshm$t4f1m<-as.numeric(datatshm$t4f1m)
datatshm$t4f3m<-as.numeric(datatshm$t4f3m)
summary(datatshm)


datacosmeticm<- datamicro[ ,c(1, 23:27)]
str(datacosmeticm)
summary(datacosmeticm)


datasymtm<-datamicro[, c(1, 29:33)]
str(datasymtm)
datasymtm$sympt1m<-as.numeric(datasymtm$sympt1m)


datareducm<-datamicro[,c(1, 20:22)]
str(datareducm)
datareducm$red1m<-as.numeric(datareducm$red1m)
datareducm$red3m<-as.numeric(datareducm$red3m)
summary(datareducm)


datadiametrom<-datamicro[, c(1:5)]
names(datadiametrom)[2]<- "diametrobasal"
names(datadiametrom)[3]<- "diametro1m"
names(datadiametrom)[4]<- "diametro3m"
names(datadiametrom)[5]<- "diametro6m"
str(datadiametrom)
datadiametrom$diametro1m<-as.numeric(datadiametrom$diametro1m)
summary(datadiametrom)
sd(datadiametrom$diametrobasal)
sd(datadiametrom$diametro1m)
sd(datadiametrom$diametro3m)
sd(datadiametrom$diametro6m)
sd(datadiametrom$diametro12m)
```


```{r analysis bocio,echo=FALSE, include=FALSE}
shapiro.test(datavol$vol1m - datavol$volbasal)
shapiro.test(datavol$vol3m - datavol$volbasal)
shapiro.test(datavol$vol6m - datavol$volbasal)
shapiro.test(datavol$vol12m - datavol$volbasal)

t.test( datavol$vol1m,
        datavol$volbasal,
        alternative = "two.sided",
        paired = TRUE )

t.test( datavol$vol3m,
        datavol$volbasal,
        alternative = "two.sided",
        paired = TRUE )

t.test( datavol$vol6m,
        datavol$volbasal,
        alternative = "two.sided",
        paired = TRUE )

t.test( datavol$vol12m,
        datavol$volbasal,
        alternative = "two.sided",
        paired = TRUE )


t.test( datadiametro$diametro1m,
        datadiametro$diametrobasal,
        alternative = "two.sided",
        paired = TRUE )

t.test( datadiametro$diametro3m,
        datadiametro$diametrobasal,
        alternative = "two.sided",
        paired = TRUE )

t.test( datadiametro$diametro6m,
        datadiametro$diametrobasal,
        alternative = "two.sided",
        paired = TRUE )

t.test( datadiametro$diametro12m,
        datadiametro$diametrobasal,
        alternative = "two.sided",
        paired = TRUE )


t.test( datareduc$red3m,
        datareduc$red1m,
        alternative = "two.sided",
        paired = TRUE )

t.test( datareduc$red6m,
        datareduc$red1m,
        alternative = "two.sided",
        paired = TRUE )

t.test( datareduc$red12m,
        datareduc$red1m,
        alternative = "two.sided",
        paired = TRUE )


t.test( datatsh$tsh1m,
        datatsh$tshbasal,
        alternative = "two.sided",
        paired = TRUE )

t.test( datatsh$tsh3m,
        datatsh$tshbasal,
        alternative = "two.sided",
        paired = TRUE )

t.test( datatsh$tsh6m,
        datatsh$tshbasal,
        alternative = "two.sided",
        paired = TRUE )

t.test( datatsh$tsh12m,
        datatsh$tshbasal,
        alternative = "two.sided",
        paired = TRUE )


t.test( datacosmetic$cosm1m,
        datacosmetic$cosmbasal,
        alternative = "two.sided",
        paired = TRUE )

t.test( datacosmetic$cosm3m,
        datacosmetic$cosmbasal,
        alternative = "two.sided",
        paired = TRUE )
t.test( datacosmetic$cosm6m,
        datacosmetic$cosmbasal,
        alternative = "two.sided",
        paired = TRUE )
t.test( datacosmetic$cosm12m,
        datacosmetic$cosmbasal,
        alternative = "two.sided",
        paired = TRUE )


t.test( datasymt$sympt1m,
        datasymt$symptbasal,
        alternative = "two.sided",
        paired = TRUE )
t.test( datasymt$sympt3m,
        datasymt$symptbasal,
        alternative = "two.sided",
        paired = TRUE )
t.test( datasymt$sympt6m,
        datasymt$symptbasal,
        alternative = "two.sided",
        paired = TRUE )
t.test( datasymt$sympt12m,
        datasymt$symptbasal,
        alternative = "two.sided",
        paired = TRUE )
```

```{r analysis micro,echo=FALSE, include=FALSE}
shapiro.test(datavolm$vol1m - datavolm$volbasal)
shapiro.test(datavolm$vol3m - datavolm$volbasal)
shapiro.test(datavolm$vol6m - datavolm$volbasal)
# shapiro.test(datavolm$vol12m - datavolm$volbasal) #No hay datos en datavolm$vol12m

t.test( datavolm$vol1m,
        datavolm$volbasal,
        alternative = "two.sided",
        paired = TRUE )

t.test( datavolm$vol3m,
        datavolm$volbasal,
        alternative = "two.sided",
        paired = TRUE )

t.test( datavolm$vol6m,
        datavolm$volbasal,
        alternative = "two.sided",
        paired = TRUE )

#t.test( datavolm$vol12m,
 #       datavolm$volbasal,
  #      alternative = "two.sided",
   #     paired = TRUE )  #No hay datos en datavolm$vol12m


t.test( datadiametrom$diametro1m,
        datadiametrom$diametrobasal,
        alternative = "two.sided",
        paired = TRUE )

t.test( datadiametrom$diametro3m,
        datadiametrom$diametrobasal,
        alternative = "two.sided",
        paired = TRUE )

t.test( datadiametrom$diametro6m,
        datadiametrom$diametrobasal,
        alternative = "two.sided",
        paired = TRUE )

# t.test( datareducm$red3m,
  #      datareducm$red1m,
   #     alternative = "two.sided",
    #    paired = TRUE ) #No hay datos suficientes dice el error

#t.test( datareducm$red6m,
 #       datareducm$red1m,
  #      alternative = "two.sided",
   #     paired = TRUE ) #No hay datos suficientes dice el error

t.test( datatshm$tsh3m,
        datatshm$tsh1m,
        alternative = "two.sided",
        paired = TRUE )

# t.test( datatshm$tsh6m,
  #      datatshm$tsh1m,
   #     alternative = "two.sided",
    #    paired = TRUE ) # Error: data are essentially constant

#t.test( datatshm$tsh12m,
 #       datatshm$tsh1m,
  #      alternative = "two.sided",
   #     paired = TRUE ) #no hay datos en tshm12m


t.test( datacosmeticm$cosm1m,
        datacosmeticm$combasal,
        alternative = "two.sided",
        paired = TRUE )

t.test( datacosmeticm$cosm3m,
        datacosmeticm$combasal,
        alternative = "two.sided",
        paired = TRUE )

t.test( datacosmeticm$cosm6m,
        datacosmeticm$combasal,
        alternative = "two.sided",
        paired = TRUE )

t.test( datacosmeticm$cosm12m,
        datacosmeticm$combasal,
        alternative = "two.sided",
        paired = TRUE )


t.test( datasymtm$sympt1m,
        datasymtm$symptbasal,
        alternative = "two.sided",
        paired = TRUE )
t.test( datasymtm$sympt3m,
        datasymtm$symptbasal,
        alternative = "two.sided",
        paired = TRUE )
t.test( datasymtm$sympt6m,
        datasymtm$symptbasal,
        alternative = "two.sided",
        paired = TRUE )
t.test( datasymtm$sympt12m,
        datasymtm$symptbasal,
        alternative = "two.sided",
        paired = TRUE )
```

<br>
<h2>Radiofrequency Ablation for Thyroid Nodules in Ecuador: Cross-sectional study</h2>


<details>

<summary><b>Figure A -</b> Benign tumor volumen (mL) after Radiofrequency Ablation </summary>
<br>

```{r graphs, echo=FALSE, fig.height = 9.8, fig.width = 13.5, warning=F, results=F}
gvol <- datavol[,-c(2:4)] #Remove non-useful cols

#Para interpretar el grafico usamos valores perdidos y disminucion del volumen del tumor
#PRIMERO SI ES QUE AL 1, 3, 6 Y 12 MESES DISMINUYO
one <- ifelse(gvol$vol12m<gvol$volbasal, yes = "GOOD", no = "N")
three <- ifelse(gvol$vol6m<gvol$volbasal, yes = "GOOD", no = "N") 
six <- ifelse(gvol$vol3m<gvol$volbasal, yes = "GOOD", no = "N") 
twelve <- ifelse(gvol$vol1m<gvol$volbasal, yes = "GOOD", no = "N")

#segundo cuantos casos no se reportaban EN CADA CITA CONTROL
summary(gvol)

  #Subset of datos que se reportaron hasta el valor basal
gvolb <- subset(gvol, volbasal >= 0 & is.na(vol1m) & is.na(vol3m) & is.na(vol6m) & is.na(vol12m))

#Subset of datos que se reportaron hasta el primer  mes
gvol1 <- subset(gvol, volbasal >= 0 & vol1m >= 0 & is.na(vol3m) & is.na(vol6m) & is.na(vol12m))

#Subset of datos que se reportaron hasta el tercer  mes
gvol3 <- subset(gvol, volbasal >= 0 & vol1m >= 0  & vol3m >= 0 & is.na(vol6m) & is.na(vol12m))
new_row = list(id = NA, volbasal=NA, vol1m = NA, vol3m = NA, vol6m = NA, vol12m = NA)
gvol3 <- rbind(gvol3,new_row)

#Subset of datos que se reportaron hasta el sexto  mes
gvol6 <- subset(gvol, volbasal >= 0 & vol1m >= 0 & vol3m >= 0  & vol6m >= 0 & is.na(vol12m)) #
gvol6a <- subset(gvol, volbasal >= 0 & is.na(vol1m) & is.na(vol3m) & vol6m >= 0 & is.na(vol12m))
gvol6 <- merge(gvol6, gvol6a, by = c("id", "volbasal", "vol1m", "vol3m", "vol6m", "vol12m"), all = T)
gvol6b <- subset(gvol, volbasal >= 0 & vol1m >= 0 & is.na(vol3m) & vol6m >= 0 & is.na(vol12m))
gvol6 <- merge(gvol6, gvol6b, by = c("id", "volbasal", "vol1m", "vol3m", "vol6m", "vol12m"), all = T)

#Subset of datos que se reportaron hasta el 12vo mes
gvol12 <- subset(gvol, volbasal >= 0 & vol1m >= 0 & vol3m >= 0  & vol6m >= 0 & vol12m >= 0)
gvol12b <- subset(gvol, volbasal >= 0 & is.na(vol1m) & is.na(vol3m) & is.na(vol6m) & vol12m >= 0)
gvol12 <- merge(gvol12, gvol12b, by = c("id", "volbasal", "vol1m", "vol3m", "vol6m", "vol12m"), all = T)
gvol12c <- subset(gvol, volbasal >= 0 & vol1m >= 0 & is.na(vol3m) & vol6m >= 0 & vol12m >= 0)
gvol12 <- merge(gvol12, gvol12c, by = c("id", "volbasal", "vol1m", "vol3m", "vol6m", "vol12m"), all = T)
gvol12d <- subset(gvol, volbasal >= 0 & is.na(vol1m) & is.na(vol3m) & vol6m >= 0 & vol12m >= 0)
gvol12 <- merge(gvol12, gvol12d, by = c("id", "volbasal", "vol1m", "vol3m", "vol6m", "vol12m"), all = T)

#Convertimos cols a rows y rows a cols 
gvolb <- gvolb%>%pivot_longer(-id, names_to = "mes", values_to = "valor")
gvolb <- gvolb%>%pivot_wider(names_from = id, values_from = valor)
gvolb <- gvolb[,-1] #rows: 1 = volbasal, 2 = vol1m, 3 = vol3m, 4 = vol6m, 5 = vol12m

gvol1 <- gvol1%>%pivot_longer(-id, names_to = "mes", values_to = "valor")
gvol1 <- gvol1%>%pivot_wider(names_from = id, values_from = valor)
gvol1 <- gvol1[,-1] #rows: 1 = volbasal, 2 = vol1m, 3 = vol3m, 4 = vol6m, 5 = vol12m

gvol3 <- gvol3%>%pivot_longer(-id, names_to = "mes", values_to = "valor")
gvol3 <- gvol3%>%pivot_wider(names_from = id, values_from = valor)
gvol3 <- gvol3[,-1] #rows: 1 = volbasal, 2 = vol1m, 3 = vol3m, 4 = vol6m, 5 = vol12m

gvol6 <- gvol6%>%pivot_longer(-id, names_to = "mes", values_to = "valor")
gvol6 <- gvol6%>%pivot_wider(names_from = id, values_from = valor)
gvol6 <- gvol6[,-1] #rows: 1 = volbasal, 2 = vol1m, 3 = vol3m, 4 = vol6m, 5 = vol12m

gvol12 <- gvol12%>%pivot_longer(-id, names_to = "mes", values_to = "valor")
gvol12 <- gvol12%>%pivot_wider(names_from = id, values_from = valor)
gvol12 <- gvol12[,-1] #rows: 1 = volbasal, 2 = vol1m, 3 = vol3m, 4 = vol6m, 5 = vol12m

#Formato para ggplot lineas
gvolb <- data.frame(x = seq_along(gvolb[, c(1,2,3,4,5)]), gvolb)
gvolb <- melt(gvolb, id.vars = "x")
names(gvolb)[1] <- "Months"
names(gvolb)[3] <- "value"
gvolb <- na.omit(gvolb)

gvol1 <- data.frame(x = seq_along(gvol1[, c(1,2,3,4,5)]), gvol1)
gvol1 <- melt(gvol1, id.vars = "x")
names(gvol1)[1] <- "Months"
names(gvol1)[3] <- "value"
gvol1 <- na.omit(gvol1)

colnames(gvol3) <- c(1,2,3,4,5)
gvol3 <- data.frame(x = seq_along(gvol3[, c(1,2,3,4,5)]), gvol3)
gvol3 <- melt(gvol3, id.vars = "x")
names(gvol3)[1] <- "Months"
names(gvol3)[3] <- "value"
gvol3 <- na.omit(gvol3)

gvol6 <- data.frame(x = seq_along(gvol6[, c(1,2,3,4,5)]), gvol6)
gvol6 <- melt(gvol6, id.vars = "x")
names(gvol6)[1] <- "Months"
names(gvol6)[3] <- "value"
gvol6 <- na.omit(gvol6)

gvol12 <- data.frame(x = seq_along(gvol12[, c(1,2,3,4,5)]), gvol12)
gvol12 <- melt(gvol12, id.vars = "x")
names(gvol12)[1] <- "Months"
names(gvol12)[3] <- "value"
gvol12 <- na.omit(gvol12)


#Grafico 
labels <- c("0", "1", "3", "6", "12")
rownames(gvolb) <- NULL
rownames(gvol1) <- NULL
rownames(gvol3) <- NULL
rownames(gvol6) <- NULL
rownames(gvol12) <- NULL

Case_follow_up <- list('#000000', '#8F3D38', '#258D19', '#E44F9C', '#00BFC4')

GRAPH <- ggplot(gvol1, aes(x=Months, y=value, groupo = variable)) + 
  geom_point(data = gvolb, aes(x=Months, y=value, color=Case_follow_up[[1]]), size = 4.5) +
  geom_line(data=gvol1, aes(x=Months, y=value, color=Case_follow_up[[5]]), size = 1.4) +
  geom_point(data = gvol1, aes(x=Months, y=value, color=Case_follow_up[[5]]), size = 4) +
  geom_line(data=gvol3, aes(x=Months, y=value, color=Case_follow_up[[3]]), size = 1.3) +
  geom_point(data = gvol3, aes(x=Months, y=value, color=Case_follow_up[[3]]), size = 4.3) +
  geom_line(data=gvol6, aes(x=Months, y=value, color=Case_follow_up[[2]]), size = 1.2) +
  geom_point(data = gvol6, aes(x=Months, y=value, color=Case_follow_up[[2]]), size = 4.1) +
  geom_line(data=gvol12, aes(x=Months, y=value,color=Case_follow_up[[4]]), size = 1) +
  geom_point(data = gvol12, aes(x=Months, y=value, color=Case_follow_up[[4]]), size = 3.9) +
  # theme(legend.position='none') + # Eliminamos legenda de cada id con su color
  scale_x_continuous(label = labels) +
  theme(legend.position = c(0.8, 0.8), legend.background = element_rect(fill = "white"), 
        legend.key.size = unit(1.3, units = "cm")) +
  guides(color = guide_legend(override.aes = list(size = 6)))+
  scale_color_discrete("Case follow-up:    ", labels = c("Zero month", "First month",
                                                         "Third month", "Sixth month",
                                                    "Twelfth month")) +
  labs(x = "Time (Months)" , y = "Nodule volume (mL)")

GRAPH
```

</details>


<details>

<summary><b>Figure A -</b> Microadenoma volumen (mL) after Radiofrequency Ablation </summary>
<br>

```{r graphs, echo=FALSE, fig.height = 9.8, fig.width = 13.5, warning=F, results=F}
gvolm <- datavolm

#Para interpretar el grafico usamos valores perdidos y disminucion del volumen del tumor
#PRIMERO SI ES QUE AL 1, 3, 6 Y 12 MESES DISMINUYO
onem <- ifelse(gvolm$vol12m<gvolm$volbasal, yes = "GOOD", no = "N")
threem <- ifelse(gvolm$vol6m<gvolm$volbasal, yes = "GOOD", no = "N") 
sixm <- ifelse(gvolm$vol3m<gvolm$volbasal, yes = "GOOD", no = "N") 
twelvem <- ifelse(gvolm$vol1m<gvolm$volbasal, yes = "GOOD", no = "N")

#segundo cuantos casos no se reportaban EN CADA CITA CONTROL
summary(gvolm)

#Subset of datos que se reportaron hasta el valor basal
gvolbm <- subset(gvolm, volbasal >= 0 & is.na(vol1m) & is.na(vol3m) & is.na(vol6m) & is.na(vol12m))

#Subset of datos que se reportaron hasta el primer  mes
gvol1m <- subset(gvolm, volbasal >= 0 & vol1m >= 0 & is.na(vol3m) & is.na(vol6m) & is.na(vol12m))

#Subset of datos que se reportaron hasta el tercer  mes
gvol3m <- subset(gvolm, volbasal >= 0 & vol1m >= 0  & vol3m >= 0 & is.na(vol6m) & is.na(vol12m))

#Subset of datos que se reportaron hasta el sexto  mes
gvol6m <- subset(gvolm, volbasal >= 0 & vol1m >= 0 & vol3m >= 0  & vol6m >= 0 & is.na(vol12m)) #
gvol6am <- subset(gvolm, volbasal >= 0 & is.na(vol1m) & is.na(vol3m) & vol6m >= 0 & is.na(vol12m))
gvol6m <- merge(gvol6m, gvol6am, by = c("id", "volbasal", "vol1m", "vol3m", "vol6m", "vol12m"), all = T)
gvol6bm <- subset(gvolm, volbasal >= 0 & vol1m >= 0 & is.na(vol3m) & vol6m >= 0 & is.na(vol12m))
gvol6m <- merge(gvol6m, gvol6bm, by = c("id", "volbasal", "vol1m", "vol3m", "vol6m", "vol12m"), all = T)

#Subset of datos que se reportaron hasta el 12vo mes
gvol12m <- subset(gvolm, volbasal >= 0 & vol1m >= 0 & vol3m >= 0  & vol6m >= 0 & vol12m >= 0)
gvol12bm <- subset(gvolm, volbasal >= 0 & is.na(vol1m) & is.na(vol3m) & is.na(vol6m) & vol12m >= 0)
gvol12m <- merge(gvol12m, gvol12bm, by = c("id", "volbasal", "vol1m", "vol3m", "vol6m", "vol12m"), all = T)
gvol12cm <- subset(gvolm, volbasal >= 0 & vol1m >= 0 & is.na(vol3m) & vol6m >= 0 & vol12m >= 0)
gvol12m <- merge(gvol12m, gvol12cm, by = c("id", "volbasal", "vol1m", "vol3m", "vol6m", "vol12m"), all = T)
gvol12dm <- subset(gvolm, volbasal >= 0 & is.na(vol1m) & is.na(vol3m) & vol6m >= 0 & vol12m >= 0)
gvol12m <- merge(gvol12m, gvol12dm, by = c("id", "volbasal", "vol1m", "vol3m", "vol6m", "vol12m"), all = T)

#Convertimos cols a rows y rows a cols 
gvolbm <- gvolbm%>%pivot_longer(-id, names_to = "mes", values_to = "valor")
gvolbm <- gvolbm%>%pivot_wider(names_from = id, values_from = valor)
gvolbm <- gvolbm[,-1] #rows: 1 = volbasal, 2 = vol1m, 3 = vol3m, 4 = vol6m, 5 = vol12m
new_col1bm = list(NA)
new_col2bm = list(NA)
new_col3bm = list(NA)
gvolbm <- cbind(gvolbm, new_col1bm, new_col2bm, new_col3bm)

gvol1m <- gvol1m%>%pivot_longer(-id, names_to = "mes", values_to = "valor")
gvol1m <- gvol1m%>%pivot_wider(names_from = id, values_from = valor)
gvol1m <- gvol1m[,-1] #rows: 1 = volbasal, 2 = vol1m, 3 = vol3m, 4 = vol6m, 5 = vol12m
gvol1m <- cbind(gvol1m, new_col1bm, new_col2bm)

gvol3m <- gvol3m%>%pivot_longer(-id, names_to = "mes", values_to = "valor")
gvol3m <- gvol3m%>%pivot_wider(names_from = id, values_from = valor)
gvol3m <- gvol3m[,-1] #rows: 1 = volbasal, 2 = vol1m, 3 = vol3m, 4 = vol6m, 5 = vol12m
gvol3m <- cbind(gvol3m, new_col1bm, new_col2bm, new_col3bm)

gvol6m <- gvol6m%>%pivot_longer(-id, names_to = "mes", values_to = "valor")
gvol6m <- gvol6m%>%pivot_wider(names_from = id, values_from = valor)
gvol6m <- gvol6m[,-1] #rows: 1 = volbasal, 2 = vol1m, 3 = vol3m, 4 = vol6m, 5 = vol12m
gvol6m <- cbind(gvol6m, new_col1bm, new_col2bm)

gvol12m <- gvol12m%>%pivot_longer(-id, names_to = "mes", values_to = "valor")
gvol12m <- gvol12m%>%pivot_wider(names_from = id, values_from = valor)
gvol12m <- gvol12m[,-1] #rows: 1 = volbasal, 2 = vol1m, 3 = vol3m, 4 = vol6m, 5 = vol12m

#Formato para ggplot lineas
gvolbm <- data.frame(x = seq_along(gvolbm[, c(1,2,3,4,5)]), gvolbm)
gvolbm <- melt(gvolbm, id.vars = "x")
names(gvolbm)[1] <- "Months"
names(gvolbm)[3] <- "value"
gvolb <- na.omit(gvolbm)

gvol1m <- data.frame(x = seq_along(gvol1m[, c(1,2,3,4,5)]), gvol1m)
gvol1m <- melt(gvol1m, id.vars = "x")
names(gvol1m)[1] <- "Months"
names(gvol1m)[3] <- "value"
gvol1 <- na.omit(gvol1m)

colnames(gvol3m) <- c(1,2,3,4,5)
gvol3m <- data.frame(x = seq_along(gvol3m[, c(1,2,3,4,5)]), gvol3m)
gvol3m <- melt(gvol3m, id.vars = "x")
names(gvol3m)[1] <- "Months"
names(gvol3m)[3] <- "value"
gvol3m <- na.omit(gvol3m)

gvol6m <- data.frame(x = seq_along(gvol6m[, c(1,2,3,4,5)]), gvol6m)
gvol6m <- melt(gvol6m, id.vars = "x")
names(gvol6m)[1] <- "Months"
names(gvol6m)[3] <- "value"
gvol6m <- na.omit(gvol6m)

names(gvol12m)[1] <- "Months"
names(gvol12m)[3] <- "value"
gvol12m <- na.omit(gvol12m)


#Grafico 
labels <- c("0", "1", "3", "6", "12")
rownames(gvolbm) <- NULL
rownames(gvol1m) <- NULL
rownames(gvol3m) <- NULL
rownames(gvol6m) <- NULL
rownames(gvol12m) <- NULL

Case_follow_up <- list('#000000', '#8F3D38', '#258D19', '#E44F9C', '#00BFC4')

GRAPHM <- ggplot(gvol1m, aes(x=Months, y=value, groupo = variable)) + 
  geom_point(data = gvolbm, aes(x=Months, y=value, color=Case_follow_up[[1]]), size = 4.5) +
  geom_line(data=gvol1m, aes(x=Months, y=value, color=Case_follow_up[[5]]), size = 1.4) +
  geom_point(data = gvol1m, aes(x=Months, y=value, color=Case_follow_up[[5]]), size = 4) +
  geom_line(data=gvol3m, aes(x=Months, y=value, color=Case_follow_up[[3]]), size = 1.3) +
  geom_point(data = gvol3m, aes(x=Months, y=value, color=Case_follow_up[[3]]), size = 4.3) +
  geom_line(data=gvol6m, aes(x=Months, y=value, color=Case_follow_up[[2]]), size = 1.2) +
  geom_point(data = gvol6m, aes(x=Months, y=value, color=Case_follow_up[[2]]), size = 4.1) +
  # theme(legend.position='none') + # Eliminamos legenda de cada id con su color
  scale_x_continuous(label = labels) +
  theme(legend.position = c(0.8, 0.8), legend.background = element_rect(fill = "white"), 
        legend.key.size = unit(1.3, units = "cm")) +
  guides(color = guide_legend(override.aes = list(size = 6)))+
  scale_color_discrete("Case follow-up:    ", labels = c("Zero month", "First month",
                                                         "Third month", "Sixth month")) +
  labs(x = "Time (Months)" , y = "Nodule volume (mL)")

GRAPHM
```

</details>
